name: rei 7

on:
  workflow_dispatch:
  repository_dispatch:
    types: ["rei7"]
  
jobs:
  Furia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary

          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /usr/share/keyrings/google-chrome-keyring.gpg
          echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt update -y
          sudo apt install -y gconf-service libasound2 libatk1.0-0 libcairo2 libcups2 libfontconfig1 libgdk-pixbuf2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libxss1 fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils
          sudo apt install -y google-chrome-stable

      - name: Clone repo
        run: |
          git clone https://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@github.com/ZyamHunter/furia-base.git
      
      - name: Execute file
        run: |
          cd furia-base
          python ./rei/rei7.py
